name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Check code style
        run: pnpm run format:check

      - name: Run linter
        run: pnpm run lint

      - name: Type check
        run: pnpm run typecheck

      - name: Generate coverage
        run: pnpm run coverage

      - uses: codecov/codecov-action@v3

  deploy:
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - run: pnpm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
